# Generated by Django 5.1.5 on 2025-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(False, 'не проверено'), (True, 'проверено')], default=0, verbose_name='Проверено'),
        ),
    ]
